spring.application.name=eccomerce_notification
server.port=8081

# MongoDB (same Atlas as main app)
spring.data.mongodb.uri= mongodb+srv://czsubham_db_user:lRKdkfga0ptPaUUG@cluster0.k5agxsq.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=eccomerce

# RedPanda Cloud
spring.kafka.bootstrap-servers=d80205rqq91v3m2mvkhg.any.us-east-1.mpx.prd.cloud.redpanda.com:9092
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="eccomerce_user" password="TestKafkaCz@123";

# Consumer
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.eccomerce_notification.event.NotificationEvent

# Producer (for DLQ)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=czsubham@gmail.com
spring.mail.password=gpdbsrvbsuuazlln
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#//mail -> bpzt egry fvmp dalv

# App
app.email.from=czsubhaml@gmail.com
app.email.from-name=ShopIndia
logging.level.org.springframework.security=DEBUG